#!/bin/bash

source /opt/venv/bin/activate

vllm serve Qwen/Qwen2.5-Coder-3B-Instruct \
    --host 0.0.0.0 \
    --port 8000 \
    --kv-transfer-config \
    '{"kv_connector":"LMCacheConnectorV1", "kv_role":"kv_both"}'

